### ISSUE TITLE
Fix the OVA so it works with Avalon 6.3

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-packer#5]
Streaming is not working on Firefox because it doesn't have H264 codec. OpenH246 did not help. 

The simplest way to get streaming is to install Chrome, preferably when the OVA starts up because Chrome isn't redistributable.

We also need to install and run everything as a regular user because running Chrome under root has a bunch of annoyances (keyring)

**Comment by cjcolvar** [comment]
Another approach is to not expect to be able to stream within the linux environment and only access it from the host via bridged networking or something like it.

Or switch the encoding to be OGV for the ova only?

**Comment by cjcolvar** [comment]
waiting on testing of https://github.com/avalonmediasystem/avalon/issues/2469

**Comment by joncameron** [comment]
We need a PR into avalon-packer to move the changes into master before closing this issue.
